local _, L = ...;
if GetLocale() ~= "ruRU" then
 L["Актуальная статистика на mythicminus.com"] = "Current statistics on mythicminus.com"
 L["Базы сильно устарели! Требуется обновление! Загрузите последнюю версию"] = "The database are outdated! An update is required! download the latest version"
 L["Побеждённые боссы:"] = "Defeated bosses:"
 L["Лучшие прохождения:"] = "Best keys:"
 L["Лучший за сезон:"] = "Best key:"
 L["Подождите..."] = "Loading..."
 L["Ключи в таймер:"] = "In time, level:"
 L["Рекорд лидера группы:"] = "Best leader's key"
 L["Ваш рекорд в текущем подземелье:"] = "Your best in the current dungeon:"

 L["ПР"] = "LFR"
 L["ОБ"] = "N"
 L["Г"] = "HC"
 L["Э"] = "M"

 L["Лучшие прохождения лидера группы:"] = "The leader's best runs:"
 L["Атал'дазар"] = "Atal'dazar"
 L["Атал'Дазар"] = "Atal'dazar"
 L["Подгнилье"] = "The Underrot"
 L["Храм Сетралисс"] = "Temple of Sethralis"
 L["ЗОЛОТАЯ ЖИЛА!!!"] = "The MOTHERLODE!!"
 L["ЗОЛОТАЯ ЖИЛА!!"] = "The MOTHERLODE!!"
 L["Гробница королей"] = "Kings' Rest"
 L["Вольная гавань"] = "Freehold"
 L["Вольная Гавань"] = "Freehold"
 L["Святилище Штормов"] = "Shrine of the Storm"
 L["Тол Дагор"] = "Tol Dagor"
 L["Усадьба Уейкрестов"] = "Waycrest Manor"
 L["Усадьба Уэйкрестов"] = "Waycrest Manor"
 L["Осада Боралуса"] = "Siege of Boralus"
 L["Операция Мехагон - свалка"] = "Mechagon Junkyard"
 L["Операция Мехагон - мастерская"] = "Mechagon Workshop"
 
 L["Ни'алота:"] = "Ny'alotha:"
 L["Гневион"] = "Wrathion"
 L["Маут"] = "Maut"
 L["Пророк Скитра"] = "Prophet Skitra"
 L["Темный инквизитор Занеш"] = "Dark Inquisitor Xanesh"
 L["Коллективный разум"] = "Hivemind"
 L["Шад'хар ненасытный"] = "Shad'har the Insatiable"
 L["Дест'агат"] = "Drest'agath"
 L["Ил'гинот"] = "Il'gynoth"
 L["Вексиона"] = "Vexiona"
 L["Ра-ден"] = "Ra-den"
 L["Панцырь Н'зота"] = "Carapace of N'Zoth"
 L["Н'зот заразитель" ] = "N'Zoth, the Corruptor"

end